# Generated by Django 4.1 on 2022-08-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='genger',
            new_name='gender',
        ),
    ]
